In [262]:
import numpy as np

# Creating Array:

In [263]:
# 0D array
arr=np.array(42)
print(arr)

42


In [264]:
# 1D array
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [265]:
# 2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [266]:
# 3D array
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [267]:
# Check Dimensions
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [268]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


# Accessing array elements: 

In [269]:
# 1D Array
nums=np.array([1,2,3,4,5])
print(nums[1]+nums[2])

# Last element => negative index
print(nums[-2]+nums[-1])

5
9


In [270]:
# 2D Array
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(nums[1,3])

# Last element => negative index
print(nums[1,-1]) 

9
10


In [271]:
# 3D Array
nums=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[100,200,300]]])
print(nums)
print("\nAns:",nums[1,0,2])

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [100 200 300]]]

Ans: 30


# Array Slicing:

In [272]:
# 1D Array
v=np.array([1,2,3,4,5,6,7])
print(v[:4])
print(v[4:])
print(v[:-2])

# Step
print(v[:5:2])

[1 2 3 4]
[5 6 7]
[1 2 3 4 5]
[1 3 5]


In [273]:
# 2D Array
v=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(v[:,1:3])
print(v[1,1:2])
print(v[1,1:4])
print(v[0:2,2])
print(v[0:2,1:4])

[[2 3]
 [7 8]]
[7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# NumPy Data Types:

In [274]:
# Checking datatypes
print(v.dtype)

int32


In [275]:
v=np.array(['apple', 'banana', 'cherry'])
print(v.dtype)

# U -> unicode string

<U6


In [276]:
# Creating array with defined datatype

# S-> String
v=np.array([1,2,3,4],dtype='S')
print(v)
print(v.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [277]:
v=np.array([1,2,3,4],dtype='i4')
# i4 means integer of 4 bytes
print(v)
print(v.dtype)

[1 2 3 4]
int32


In [278]:
# But what if this type casting fails, then NumPy raises an error
v=np.array(['a','2','3'],dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# Changing the Data Type of an Array

In [279]:
v=np.array([1.1, 2.1, 3.1])
print(v.dtype)
newv=v.astype(int)
# newv=v.astype('i')
print(newv.dtype)

float64
int32


In [280]:
print(v.dtype)
newv=v.astype(bool)
print(newv.dtype)

float64
bool


# Array Copy vs View 

In [281]:
# The copy owns the data and any changes made to the copy will not affect original 
# array, and any changes made to the original array will not affect the copy.
v=np.array([1,2,3,4,5])
x=v.copy()
v[0]=42
print(v)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [282]:
# The view does not own the data and any changes made to the view will affect 
# the original array, and any changes made to the original array will affect the view.
y=v.view()
print(y)
y[0]=10
print(v)
print(y)

[42  2  3  4  5]
[10  2  3  4  5]
[10  2  3  4  5]


In [283]:
# Check if Array Owns its Data
# attribute base that returns None if the array owns the data.
print(v.base)
print(x.base)
print(y.base)

None
None
[10  2  3  4  5]


In [284]:
# Shape
print(v.shape)
v=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(v.shape)

(5,)
(2, 4)


# Array Reshaping

In [285]:
# 1D -> 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new=arr.reshape(4,3)
print(arr)
print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [286]:
# 1D -> 3D
new = arr.reshape(2,3,2)
print(new)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

The multiplication of the reshape parameters must be equal to the no of elements.

In [287]:
print(arr)
print("Base or parent:",arr.reshape(3,4).base)
# parent is arr

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Base or parent: [ 1  2  3  4  5  6  7  8  9 10 11 12]


# Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

The logic is the last parameter will be calculated by making the product of parameters and no of elements equal.

In [288]:
new = arr.reshape(2,2,-1)
print(new)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Flattening the arrays

In [289]:
# 2D -> 1D
arr=np.array([[1, 2, 3], [4, 5, 6]])
new = arr.reshape(-1)
print(new)

# OR
new = arr.reshape(6)
print(new)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


# Array Iteration

In [290]:
# 1D array
arr = np.array([1, 2, 3])
for x in arr: 
    print(x)

1
2
3


In [291]:
# 2D 
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

print()

for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]

1
2
3
4
5
6


In [292]:
# 3D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

print()

for x in arr:
    for y in x:
        print(y)

print()

for x in arr:
    for y in x:
        for z in y:
            print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]

1
2
3
4
5
6
7
8
9
10
11
12


In [293]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types

In [294]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr,flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


# Iterating With Different Step Size

In [295]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


# Enumerated Iteration Using ndenumerate()

In [296]:
arr = np.array([1, 2, 3])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [297]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Index","Element")
for idx,x in np.ndenumerate(arr):
    print(idx,x)

Index Element
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining Array

In [298]:
# 1D array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [299]:
# 2D array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

print()

arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [300]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr= np.stack((arr1,arr2),axis=1)
print(arr)

print()

arr= np.stack((arr1,arr2),axis=0)
print(arr)

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]]


In [301]:
# Horizontal(Rows) stacking
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [302]:
# Vertical(Column) stacking
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [303]:
# Depth(Height) stacking
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting Arrays

In [304]:
# 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr,3)
print(new)

print()

print(new[0])
print(new[1])
print(new[2])

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]
[3 4]
[5 6]


In [305]:
# 2D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
new = np.array_split(arr,3)
print(new)

print()

print(new[0])
print(new[1])
print(new[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [306]:
# Splitting along row
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new =np.array_split(arr,3,axis=1)
print(new)

print()

print(new[0])
print(new[1])
print(new[2])

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [307]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching arrays

In [308]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x= np.where(arr==4)
print(x)

print()

y=np.where(arr%2==0)
print(y)

(array([3, 5, 6], dtype=int64),)

(array([1, 3, 5, 6], dtype=int64),)


In [309]:
# If array is sorted, binary search is applied
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

# Now generally search begins from left, to start seach from right
y=np.searchsorted(arr,7,side='right')
print('Right',y)

1
Right 2


In [310]:
# To search multiple values
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)
# The return value is an array: [1 2 3] containing the three indexes 
# where 2, 4, 6 would be inserted in the original array to maintain the order.

[1 2 3]


# Sorting arrays



In [311]:
# 1D
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

arr = np.array([True, False, True])
print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


In [312]:
# 2D
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering arrays

Getting some elements out of an existing array and 
creating a new array out of them is called filtering.

In [313]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
new = arr[x]
print(new)

[41 43]


In [314]:
# Create a filter array that will return only values higher than 42
arr = np.array([41, 42, 43, 44])
new = []
for ele in arr:
    if ele > 42:
        new.append(True)
    else :
        new .append(False)
print(arr)
print(new)

# Filtered array
filter_array=arr[new]
print(filter_array)

print()

# OR
filter_array=arr>42
print(filter_array)
filter_array=arr[filter_array]
print(filter_array)

[41 42 43 44]
[False, False, True, True]
[43 44]

[False False  True  True]
[43 44]


In [315]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
new = []
for ele in arr:
    if ele%2==0:
        new.append(ele)
print(new)

print()

# OR
new=arr[arr%2==0]
print(new)

[2, 4, 6]

[2 4 6]
