In [87]:
import numpy as np

# Creating Array:

In [88]:
# 0D array
arr=np.array(42)
print(arr)

42


In [89]:
# 1D array
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [90]:
# 2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [91]:
# 3D array
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [92]:
# Check Dimensions
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [93]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


# Accessing array elements: 

In [94]:
# 1D Array
nums=np.array([1,2,3,4,5])
print(nums[1]+nums[2])

# Last element => negative index
print(nums[-2]+nums[-1])

5
9


In [95]:
# 2D Array
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(nums[1,3])

# Last element => negative index
print(nums[1,-1]) 

9
10


In [96]:
# 3D Array
nums=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[100,200,300]]])
print(nums)
print("\nAns:",nums[1,0,2])

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [100 200 300]]]

Ans: 30


# Array Slicing:

In [97]:
# 1D Array
v=np.array([1,2,3,4,5,6,7])
print(v[:4])
print(v[4:])
print(v[:-2])

# Step
print(v[:5:2])

[1 2 3 4]
[5 6 7]
[1 2 3 4 5]
[1 3 5]


In [98]:
# 2D Array
v=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(v[:,1:3])
print(v[1,1:2])
print(v[1,1:4])
print(v[0:2,2])
print(v[0:2,1:4])

[[2 3]
 [7 8]]
[7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# NumPy Data Types:

In [99]:
# Checking datatypes
print(v.dtype)

int32


In [100]:
v=np.array(['apple', 'banana', 'cherry'])
print(v.dtype)

# U -> unicode string

<U6


In [102]:
# Creating array with defined datatype

# S-> String
v=np.array([1,2,3,4],dtype='S')
print(v)
print(v.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [104]:
v=np.array([1,2,3,4],dtype='i4')
# i4 means integer of 4 bytes
print(v)
print(v.dtype)

[1 2 3 4]
int32


In [ ]:
# But what if this type